---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rating-config"
  labels:
    app: "aspire"
    component: "rating"
data:
  ASPNETCORE_URLS: "{{ .Values.config.rating.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.rating.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.rating.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.rating.HTTP_PORTS }}"
  ConnectionStrings__ratingdb: "{{ .Values.config.rating.ConnectionStrings__ratingdb }}"
  services__keycloak__http__0: "{{ .Values.config.rating.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.rating.services__keycloak__management__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.rating.HEALTHCHECKSUI_URLS }}"
