---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "rating-secrets"
  labels:
    app: "aspire"
    component: "rating"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.rating.queue_password }}@queue:5672"
type: "Opaque"
