---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ordering-deployment"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "ordering"
    spec:
      containers:
        - image: "{{ .Values.parameters.ordering.ordering_image }}"
          name: "ordering"
          envFrom:
            - configMapRef:
                name: "ordering-config"
            - secretRef:
                name: "ordering-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.ordering.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.ordering.port_https }}"
            - name: "healthchecks"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.ordering.port_healthchecks }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app: "aspire"
      component: "ordering"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
