---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ordering-secrets"
  labels:
    app: "aspire"
    component: "ordering"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.ordering.queue_password }}@queue:5672"
type: "Opaque"
