---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gateway-service"
spec:
  type: "ClusterIP"
  selector:
    app: "aspire"
    component: "gateway"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.gateway.port_http }}"
      targetPort: "{{ .Values.parameters.gateway.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.gateway.port_https }}"
      targetPort: "{{ .Values.parameters.gateway.port_https }}"
    - name: "healthchecks"
      protocol: "TCP"
      port: "{{ .Values.parameters.gateway.port_healthchecks }}"
      targetPort: "{{ .Values.parameters.gateway.port_healthchecks }}"
