extends: ["spectral:oas", "spectral:asyncapi"]

rules:
  oas3-valid-schema-example-location-header:
    description: Disable oas3-valid-schema-example for Location header example format
    given:
      - $.paths.*.post.responses["201"].headers.Location.schema.example
    severity: off
    then:
      function: falsy
  oas3-valid-schema-example:
    given: "$"
    severity: warn
    then:
      function: truthy
