---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "notification-config"
  labels:
    app: "aspire"
    component: "notification"
data:
  ASPNETCORE_URLS: "{{ .Values.config.notification.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.notification.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.notification.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.notification.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.notification.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.notification.HTTP_PORTS }}"
  ConnectionStrings__table: "{{ .Values.config.notification.ConnectionStrings__table }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.notification.HEALTHCHECKSUI_URLS }}"
