---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "notification-secrets"
  labels:
    app: "aspire"
    component: "notification"
stringData:
  SendGrid__ApiKey: "{{ .Values.secrets.notification.api_key }}"
  SendGrid__SenderEmail: "{{ .Values.secrets.notification.sender_email }}"
  SendGrid__SenderName: "{{ .Values.secrets.notification.sender_name }}"
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.notification.queue_password }}@queue:5672"
type: "Opaque"
