---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "vectordb-secrets"
  labels:
    app: "aspire"
    component: "vectordb"
stringData:
  QDRANT__SERVICE__API_KEY: "{{ .Values.secrets.vectordb.vectordb_Key }}"
type: "Opaque"
