---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "vectordb-statefulset"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "vectordb"
    spec:
      containers:
        - image: "docker.io/qdrant/qdrant:v1.13.4"
          name: "vectordb"
          envFrom:
            - configMapRef:
                name: "vectordb-config"
            - secretRef:
                name: "vectordb-secrets"
          ports:
            - name: "grpc"
              protocol: "TCP"
              containerPort: "6334"
            - name: "http"
              protocol: "TCP"
              containerPort: "6333"
          volumeMounts:
            - name: "bookworm.apphost-62fd53aa4e-vectordb-data"
              mountPath: "/qdrant/storage"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "bookworm.apphost-62fd53aa4e-vectordb-data"
          emptyDir: {}
  selector:
    matchLabels:
      app: "aspire"
      component: "vectordb"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
