blank_issues_enabled: true
contact_links:
  - name: BookWorm Architecture Documentation
    url: https://bookwormdev.netlify.app/
    about: For knowledge about the BookWorm project, please refer to the documentation.
  - name: BookWorm Issue Tracker
    url: https://github.com/foxminchan/bookworm/issues
    about: For reporting issues with the BookWorm project, please use the issue tracker.
