name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

        Please provide as much detail as possible to help us understand your request.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem would this feature solve or what need would it fulfill?
      placeholder: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature implementation.
      placeholder: How would you like this feature to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Have you considered any alternative solutions?
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Screenshots
      description: If applicable, add mockups or screenshots to help explain your feature request.
      placeholder: Add mockups or screenshots here
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: Any additional information that might help us understand your request better
