---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "basket-config"
  labels:
    app: "aspire"
    component: "basket"
data:
  ASPNETCORE_URLS: "{{ .Values.config.basket.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.basket.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.basket.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.basket.HTTP_PORTS }}"
  ConnectionStrings__redis: "{{ .Values.config.basket.ConnectionStrings__redis }}"
  services__keycloak__http__0: "{{ .Values.config.basket.services__keycloak__http__0 }}"
  services__keycloak__management__0: "{{ .Values.config.basket.services__keycloak__management__0 }}"
  services__catalog__http__0: "{{ .Values.config.basket.services__catalog__http__0 }}"
  services__catalog__https__0: "{{ .Values.config.basket.services__catalog__https__0 }}"
  services__catalog__healthchecks__0: "{{ .Values.config.basket.services__catalog__healthchecks__0 }}"
  HEALTHCHECKSUI_URLS: "{{ .Values.config.basket.HEALTHCHECKSUI_URLS }}"
