---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "basket-secrets"
  labels:
    app: "aspire"
    component: "basket"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.basket.queue_password }}@queue:5672"
type: "Opaque"
