---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "catalog-secrets"
  labels:
    app: "aspire"
    component: "catalog"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.catalog.queue_password }}@queue:5672"
  ConnectionStrings__vectordb: "Endpoint=http://vectordb:6334;Key={{ .Values.secrets.catalog.vectordb_Key }}"
  ConnectionStrings__vectordb_http: "Endpoint=http://vectordb:6333;Key={{ .Values.secrets.catalog.vectordb_Key }}"
type: "Opaque"
