---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "finance-secrets"
  labels:
    app: "aspire"
    component: "finance"
stringData:
  ConnectionStrings__queue: "amqp://guest:{{ .Values.secrets.finance.queue_password }}@queue:5672"
type: "Opaque"
