name: BookWorm Pull Request Validation

on:
  pull_request:
    paths-ignore:
      - "**.md"
    types: [opened, synchronize, reopened]

env:
  DOTNET_VERSION: "9.0.x"

permissions:
  checks: write
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: ./.github/actions/setup
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache .NET SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.dotnet
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/global.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan
        uses: ./.github/actions/scan

      - name: Dependency Scan
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Format
        uses: ./.github/actions/format
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  style:
    name: Style
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Style
        uses: ./.github/actions/style
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  analyzers:
    name: Analyzers
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Analyzers
        uses: ./.github/actions/analyzers
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup, scan, format, style, analyzers]
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup, scan, format, style, analyzers]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
